sudo: false
language: python
python:
  - "3.4"
  - "3.5"
addons:
  apt:
    packages:
    - dbus
install:
  - pip install -r requirements.txt
script:
  - nosetests dbucket.test.test_escape
  - nosetests dbucket.test.test_match
  - nosetests dbucket.test.test_proxy
  - nosetests dbucket.test.test_xcode
